// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP_NoMRbRz5L7i2tWjYvhKJdMGQFJ7Dhk',
    appId: '1:896287167731:web:3e8d157f5b83a508185386',
    messagingSenderId: '896287167731',
    projectId: 'samir-28c3e',
    authDomain: 'samir-28c3e.firebaseapp.com',
    databaseURL: 'https://samir-28c3e-default-rtdb.firebaseio.com',
    storageBucket: 'samir-28c3e.appspot.com',
    measurementId: 'G-W0FEYH3B02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNwxHAtnM-n1918PGK4Nzme4KlcnIRgyc',
    appId: '1:896287167731:android:eb69aca05bfefb2f185386',
    messagingSenderId: '896287167731',
    projectId: 'samir-28c3e',
    databaseURL: 'https://samir-28c3e-default-rtdb.firebaseio.com',
    storageBucket: 'samir-28c3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXodcxUcMTMDjyTUDzNDNZAorF_TWhxmw',
    appId: '1:896287167731:ios:980cecf7930d0b95185386',
    messagingSenderId: '896287167731',
    projectId: 'samir-28c3e',
    databaseURL: 'https://samir-28c3e-default-rtdb.firebaseio.com',
    storageBucket: 'samir-28c3e.appspot.com',
    iosClientId:
        '896287167731-j07a2u7hiri9655eu7bbrpoudctgkagb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationOo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXodcxUcMTMDjyTUDzNDNZAorF_TWhxmw',
    appId: '1:896287167731:ios:980cecf7930d0b95185386',
    messagingSenderId: '896287167731',
    projectId: 'samir-28c3e',
    databaseURL: 'https://samir-28c3e-default-rtdb.firebaseio.com',
    storageBucket: 'samir-28c3e.appspot.com',
    iosClientId:
        '896287167731-j07a2u7hiri9655eu7bbrpoudctgkagb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationOo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP_NoMRbRz5L7i2tWjYvhKJdMGQFJ7Dhk',
    appId: '1:896287167731:web:f37124af8c82131c185386',
    messagingSenderId: '896287167731',
    projectId: 'samir-28c3e',
    authDomain: 'samir-28c3e.firebaseapp.com',
    databaseURL: 'https://samir-28c3e-default-rtdb.firebaseio.com',
    storageBucket: 'samir-28c3e.appspot.com',
    measurementId: 'G-5FYG14BQNT',
  );
}
